#!/usr/bin/env python3
"""Sync skills from upstream anthropics/skills into this fork's per-plugin layout.

Upstream is the source of truth for skill *content*. This fork keeps each plugin's
skills under plugins/<plugin>/skills/<skill>/. This script maps upstream's flat
skills/<skill>/ onto that layout, never reintroducing the source:"./" duplication.

Usage:
  sync.py --plan
  sync.py --apply [--assign SKILL=PLUGIN ...] [--new-plugin PLUGIN=DESCRIPTION ...] [--delete SKILL ...]

It never commits or pushes. After --apply, review `git diff --cached` and commit.
"""
from __future__ import annotations
import argparse, json, shutil, subprocess, sys, tempfile
from pathlib import Path

MARKER_BEGIN = "<!-- BEGIN PLUGIN-SKILLS-TABLE (auto-generated by sync-from-anthropic-repo) -->"
MARKER_END = "<!-- END PLUGIN-SKILLS-TABLE -->"

SKILL_DIR = Path(__file__).resolve().parent
STATE_PATH = SKILL_DIR / "state.json"


# ---------- repo / state ----------

def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for cand in [p, *p.parents]:
        if (cand / ".claude-plugin" / "marketplace.json").is_file():
            return cand
    sys.exit("error: could not find repo root (.claude-plugin/marketplace.json)")


def load_state() -> dict:
    return json.loads(STATE_PATH.read_text())


def save_state(state: dict) -> None:
    STATE_PATH.write_text(json.dumps(state, indent=2) + "\n")


# ---------- git helpers ----------

def git(root: Path, *args: str, check: bool = True) -> str:
    res = subprocess.run(["git", "-C", str(root), *args], text=True, capture_output=True)
    if check and res.returncode != 0:
        sys.exit(f"error: git {' '.join(args)} failed:\n{res.stderr}")
    return (res.stdout or "").strip()


def ensure_upstream(root: Path, remote: str, url: str) -> None:
    if remote not in git(root, "remote").splitlines():
        git(root, "remote", "add", remote, url)


def tree_sha(root: Path, ref: str, path: str) -> str | None:
    res = subprocess.run(["git", "-C", str(root), "rev-parse", f"{ref}:{path}"],
                         text=True, capture_output=True)
    return res.stdout.strip() if res.returncode == 0 else None


# ---------- layout scan ----------

def marketplace_path(root: Path) -> Path:
    return root / ".claude-plugin" / "marketplace.json"


def load_marketplace(root: Path) -> dict:
    return json.loads(marketplace_path(root).read_text())


def plugin_order(root: Path) -> list[str]:
    return [p["name"] for p in load_marketplace(root).get("plugins", [])]


# Fork-specific marketplace identity. Upstream's marketplace.json registers the
# name "anthropic-agent-skills" (reserved — only github.com/anthropics/* repos
# may use it) under Anthropic's owner block. This fork MUST diverge on both: the
# name is non-reserved so the fork can register, and the owner is the fork
# maintainer. These two fields are intentional fork edits; an upstream *content*
# sync must never reset them to upstream values. The guard below detects drift
# (--plan) and re-asserts the fork values (--apply) so they self-heal if a
# wholesale upstream marketplace.json ever lands. See SKILL.md.
FORK_MARKETPLACE_NAME = "spx-ant-agent-skills"
FORK_MARKETPLACE_OWNER = {"name": "Steven R.", "email": "contact@spxrogers.com"}


def marketplace_identity_drift(root: Path) -> list[str]:
    """Describe any fork-identity fields in marketplace.json that have drifted
    from the expected fork values. Empty list ⇒ identity is intact."""
    mp = load_marketplace(root)
    drift = []
    if mp.get("name") != FORK_MARKETPLACE_NAME:
        drift.append(f"name: {mp.get('name')!r} -> {FORK_MARKETPLACE_NAME!r}")
    if mp.get("owner") != FORK_MARKETPLACE_OWNER:
        drift.append(f"owner: {mp.get('owner')!r} -> {FORK_MARKETPLACE_OWNER!r}")
    return drift


def restore_marketplace_identity(root: Path) -> list[str]:
    """Re-assert the fork-specific name/owner in marketplace.json, preserving key
    order and every other field (incl. the plugins list). Returns the fields that
    were corrected (empty if already intact, in which case nothing is written)."""
    drift = marketplace_identity_drift(root)
    if not drift:
        return []
    mp = load_marketplace(root)
    mp["name"] = FORK_MARKETPLACE_NAME
    mp["owner"] = FORK_MARKETPLACE_OWNER
    marketplace_path(root).write_text(json.dumps(mp, indent=2) + "\n")
    return drift


def scan_plugins(root: Path):
    """Return (plugin -> sorted skills, skill -> plugin). Exit on a duplicate skill."""
    plugins_dir = root / "plugins"
    plugin_to_skills: dict[str, list[str]] = {}
    skill_to_plugin: dict[str, str] = {}
    if not plugins_dir.is_dir():
        return plugin_to_skills, skill_to_plugin
    for plugin in sorted(d.name for d in plugins_dir.iterdir() if d.is_dir()):
        skills_dir = plugins_dir / plugin / "skills"
        if not skills_dir.is_dir():
            continue
        names = []
        for sd in sorted(d.name for d in skills_dir.iterdir() if d.is_dir()):
            if not (skills_dir / sd / "SKILL.md").is_file():
                continue
            if sd in skill_to_plugin:
                sys.exit(f"error: skill '{sd}' appears in two plugins: "
                         f"{skill_to_plugin[sd]} and {plugin}")
            skill_to_plugin[sd] = plugin
            names.append(sd)
        plugin_to_skills[plugin] = names
    return plugin_to_skills, skill_to_plugin


def list_upstream_skills(root: Path, ref: str) -> list[str]:
    out = git(root, "ls-tree", "-d", "--name-only", f"{ref}:skills")
    return sorted(line.strip() for line in out.splitlines() if line.strip())


# ---------- pure logic (unit-tested) ----------

def classify(upstream: list[str], skill_to_plugin: dict[str, str],
             upstream_hash: dict, fork_hash: dict) -> dict:
    updated, new_unmapped, unchanged = [], [], []
    for name in upstream:
        if name in skill_to_plugin:
            if upstream_hash.get(name) != fork_hash.get(name):
                updated.append(name)
            else:
                unchanged.append(name)
        else:
            new_unmapped.append(name)
    removed = sorted(set(skill_to_plugin) - set(upstream))
    return {"updated": sorted(updated), "new_unmapped": sorted(new_unmapped),
            "removed_upstream": removed, "unchanged": sorted(unchanged)}


def render_table(order: list[str], plugin_to_skills: dict[str, list[str]]) -> str:
    lines = ["| Plugin | Skills |", "| --- | --- |"]
    seen = set()
    for plugin in order:
        if plugin in plugin_to_skills:
            seen.add(plugin)
            lines.append(f"| `{plugin}` | {', '.join(sorted(plugin_to_skills[plugin]))} |")
    for plugin in sorted(plugin_to_skills):
        if plugin not in seen:
            lines.append(f"| `{plugin}` | {', '.join(sorted(plugin_to_skills[plugin]))} |")
    return "\n".join(lines)


def update_readme_table(text: str, table: str) -> str:
    if MARKER_BEGIN not in text or MARKER_END not in text:
        sys.exit("error: README table markers not found; cannot update table.")
    pre, rest = text.split(MARKER_BEGIN, 1)
    _, post = rest.split(MARKER_END, 1)
    return f"{pre}{MARKER_BEGIN}\n{table}\n{MARKER_END}{post}"


def parse_kv(items: list[str]) -> dict:
    out = {}
    for it in items:
        if "=" not in it:
            sys.exit(f"error: expected KEY=VALUE, got '{it}'")
        k, v = it.split("=", 1)
        out[k.strip()] = v.strip()
    return out


# ---------- apply helpers ----------

def extract_upstream_skill(root: Path, ref: str, skill: str, dest: Path) -> None:
    """Replace dest with upstream skills/<skill> content (handles intra-skill deletions)."""
    with tempfile.TemporaryDirectory() as td:
        archive = subprocess.run(["git", "-C", str(root), "archive", ref, f"skills/{skill}"],
                                 capture_output=True)
        if archive.returncode != 0:
            sys.exit(f"error: git archive failed for {skill}:\n{archive.stderr.decode()}")
        tar = subprocess.run(["tar", "-x", "-C", td], input=archive.stdout)
        if tar.returncode != 0:
            sys.exit(f"error: tar extract failed for {skill}")
        src = Path(td) / "skills" / skill
        if not src.is_dir():
            sys.exit(f"error: extracted content missing for {skill}")
        if dest.exists():
            shutil.rmtree(dest)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dest))


def upstream_skill_description(root: Path, ref: str, skill: str) -> str:
    # Reads a single-line `description:` from the skill's SKILL.md frontmatter.
    # Multi-line / block YAML descriptions fall back to the generic string below.
    res = subprocess.run(["git", "-C", str(root), "show", f"{ref}:skills/{skill}/SKILL.md"],
                         text=True, capture_output=True)
    text = res.stdout if res.returncode == 0 else ""
    if text.startswith("---"):
        fm = text.split("---", 2)[1]
        for line in fm.splitlines():
            if line.strip().startswith("description:"):
                return line.split("description:", 1)[1].strip().strip('"').strip("'")
    return f"Skills plugin: {skill}"


def scaffold_plugin(root: Path, plugin: str, description: str) -> None:
    pdir = root / "plugins" / plugin
    (pdir / ".claude-plugin").mkdir(parents=True, exist_ok=True)
    (pdir / "skills").mkdir(parents=True, exist_ok=True)
    manifest = {"name": plugin, "description": description,
                "author": {"name": "Anthropic", "email": "support@anthropic.com"}}
    (pdir / ".claude-plugin" / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")
    mp = load_marketplace(root)
    if not any(p["name"] == plugin for p in mp["plugins"]):
        mp["plugins"].append({"name": plugin, "description": description,
                              "source": f"./plugins/{plugin}"})
        marketplace_path(root).write_text(json.dumps(mp, indent=2) + "\n")


# ---------- orchestration ----------

def compute(root: Path, state: dict, fork_ref: str = "HEAD"):
    remote = state.get("upstream_remote", "anthropic-upstream")
    url = state.get("upstream_url", "https://github.com/anthropics/skills.git")
    branch = state.get("upstream_branch", "main")
    ensure_upstream(root, remote, url)
    git(root, "fetch", remote, branch)
    upstream_ref = f"{remote}/{branch}"
    if tree_sha(root, upstream_ref, "skills") is None:
        sys.exit("error: upstream has no top-level skills/ tree; layout may have changed. "
                 "Aborting without changes.")
    upstream = list_upstream_skills(root, upstream_ref)
    if not upstream:
        sys.exit("error: found 0 skills upstream; aborting without changes.")
    plugin_to_skills, skill_to_plugin = scan_plugins(root)
    upstream_hash = {n: tree_sha(root, upstream_ref, f"skills/{n}") for n in upstream}
    fork_hash = {n: tree_sha(root, fork_ref, f"plugins/{skill_to_plugin[n]}/skills/{n}")
                 for n in skill_to_plugin}
    cls = classify(upstream, skill_to_plugin, upstream_hash, fork_hash)
    return remote, branch, upstream_ref, cls, plugin_to_skills, skill_to_plugin


def warn_if_dirty(root: Path) -> None:
    if git(root, "status", "--porcelain"):
        print("warning: working tree is not clean; run on a clean tree for a reviewable diff.\n",
              file=sys.stderr)


def cmd_plan(root: Path, state: dict) -> None:
    warn_if_dirty(root)
    remote, branch, upstream_ref, cls, _p2s, _s2p = compute(root, state)
    last = state.get("last_synced_sha", "")
    head = git(root, "rev-parse", upstream_ref)
    print(f"Upstream {remote}/{branch} HEAD: {head}")
    print(f"Last synced:            {last or '(none)'}")
    drift = marketplace_identity_drift(root)
    if drift:
        print("\nwarning: marketplace.json fork identity has drifted from the expected "
              "fork values; --apply will restore it:", file=sys.stderr)
        for d in drift:
            print(f"  - {d}", file=sys.stderr)
    if last and last != head:
        print("\nUpstream commits touching skills/ since last sync:")
        print(git(root, "log", "--oneline", f"{last}..{head}", "--", "skills", check=False) or "  (none)")
    for key, title in [("updated", "Updated (will sync)"),
                       ("new_unmapped", "New, unmapped (will ask)"),
                       ("removed_upstream", "Removed upstream (will ask)"),
                       ("unchanged", "Unchanged")]:
        print(f"\n{title}: {len(cls[key])}")
        for n in cls[key]:
            print(f"  - {n}")
    if not (cls["updated"] or cls["new_unmapped"] or cls["removed_upstream"]):
        print("\nAlready up to date.")


def cmd_apply(root: Path, state: dict, assigns: dict, new_plugins: dict, deletes: list[str]) -> None:
    warn_if_dirty(root)
    remote, branch, upstream_ref, cls, _p2s, skill_to_plugin = compute(root, state)
    head = git(root, "rev-parse", upstream_ref)
    for skill in assigns:
        if skill not in cls["new_unmapped"]:
            sys.exit(f"error: --assign {skill}: not a new-unmapped skill (see --plan)")
    for skill in deletes:
        if skill not in skill_to_plugin:
            sys.exit(f"error: --delete {skill}: not present in the fork")

    # Validate the README markers BEFORE mutating anything, so a misconfigured
    # README aborts cleanly with zero side effects (no half-applied tree).
    readme = root / "README.md"
    if MARKER_BEGIN not in readme.read_text() or MARKER_END not in readme.read_text():
        sys.exit("error: README table markers not found in README.md; aborting before any "
                 "filesystem changes. Add the PLUGIN-SKILLS-TABLE markers first.")
    changed = []

    for skill in cls["updated"]:
        plugin = skill_to_plugin[skill]
        extract_upstream_skill(root, upstream_ref, skill, root / "plugins" / plugin / "skills" / skill)
        changed.append(f"~{skill}")

    for skill, plugin in assigns.items():
        pdir = root / "plugins" / plugin
        if not (pdir / ".claude-plugin" / "plugin.json").is_file():
            desc = new_plugins.get(plugin) or upstream_skill_description(root, upstream_ref, skill)
            scaffold_plugin(root, plugin, desc)
        extract_upstream_skill(root, upstream_ref, skill, pdir / "skills" / skill)
        changed.append(f"+{skill}->{plugin}")

    for skill in deletes:
        shutil.rmtree(root / "plugins" / skill_to_plugin[skill] / "skills" / skill)
        changed.append(f"-{skill}")

    restored = restore_marketplace_identity(root)
    for d in restored:
        changed.append(f"marketplace:{d}")

    p2s, _ = scan_plugins(root)
    readme.write_text(update_readme_table(readme.read_text(), render_table(plugin_order(root), p2s)))

    state["last_synced_sha"] = head
    save_state(state)

    git(root, "add", "-A", "plugins", "README.md", ".claude-plugin/marketplace.json",
        str(STATE_PATH.relative_to(root)))
    print("Changed:", ", ".join(changed) or "(none)")
    print("\nStaged:")
    print(git(root, "diff", "--cached", "--stat"))
    print("\nReview `git diff --cached`, then commit. This script does not commit or push.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--plan", action="store_true")
    mode.add_argument("--apply", action="store_true")
    ap.add_argument("--assign", action="append", default=[], metavar="SKILL=PLUGIN")
    ap.add_argument("--new-plugin", action="append", default=[], metavar="PLUGIN=DESCRIPTION")
    ap.add_argument("--delete", action="append", default=[], metavar="SKILL")
    args = ap.parse_args()

    root = find_repo_root(SKILL_DIR)
    state = load_state()
    if args.plan:
        cmd_plan(root, state)
    else:
        cmd_apply(root, state, parse_kv(args.assign), parse_kv(args.new_plugin), args.delete)


if __name__ == "__main__":
    main()
